"use client"


import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { nunito } from "@/components/fonts";
import { ItemContext } from "@/context/ItemContext";
import { ChangeEvent, useState } from "react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [searchItem, setSearchItem] = useState("");
  const [searchQuery, setSearchQuery] = useState("");

  


  const handleSearchItem = (event:ChangeEvent<HTMLInputElement>) => {
    
    setSearchItem(event.target.value);
  };

  
  return (
    <html lang="en">

      <body className={`${nunito.className} antialiased`}>
        <ItemContext.Provider value={{ searchItem, setSearchItem }}>

          <Header />
          {children}
        </ItemContext.Provider>
      </body>
    </html>
  );
}
